### ISSUE TITLE
Segmentation fault in alloc_preferences()

### ISSUE THREAD

**Issue by miko** [FelipeFS/lovetext#1]
Tried to compile and run on recent archlinux. While compilation was OK, I get error when running:

```

$ ./lovetext 
[MESSAGE] Program activated.
Segmentation fault (core dumped)
$ gdb ./lovetext 
GNU gdb (GDB) 7.8.2
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./lovetext...done.
(gdb) 
(gdb) run
Starting program: /home/miko/Lua/lovetext-master/lovetext 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffec28e700 (LWP 18099)]
[MESSAGE] Program activated.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5987a85 in g_string_new () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff5987a85 in g_string_new () from /usr/lib/libglib-2.0.so.0
#1  0x000000000040e10e in alloc_preferences () at module.c:48
#2  0x0000000000406715 in main_application_activate (application=0x6271a0, 
    user_data=0x628d70) at main.c:117
#3  0x00007ffff5c3b255 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff5c4cf4c in ?? () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff5c55758 in g_signal_emit_valist ()
   from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff5c559bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#7  0x00000000004066c6 in main_application_command_line (application=0x6271a0, 
    command_line=0x7fffe4004a20, user_data=0x628d70) at main.c:102
#8  0x00007ffff073d1f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#9  0x00007ffff073cc58 in ffi_call () from /usr/lib/libffi.so.6
#10 0x00007ffff5c3ba74 in g_cclosure_marshal_generic ()
   from /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff5c3b255 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff5c4cf4c in ?? () from /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff5c55265 in g_signal_emit_valist ()
   from /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff5c559bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff5f1ede3 in ?? () from /usr/lib/libgio-2.0.so.0
#16 0x00007ffff5f20dcd in ?? () from /usr/lib/libgio-2.0.so.0
#17 0x00007ffff5f20f77 in g_application_run () from /usr/lib/libgio-2.0.so.0
#18 0x0000000000406a4b in main (argc=1, args=0x7fffffffe3d8) at main.c:188
(gdb) 
```

**Comment by FelipeFS** [comment]
I pushed a new commit with conditionals to check for NULL pointers at alloc_preferences, hopefully it will avoid errors or at least give a more detailed report, since the last report was "[MESSAGE] Program activated".

**Comment by flannelhead** [comment]
I'm still seeing a segfault even after checking out the latest fix. This time the last call is to vfprintf. Backtrace attached.

```
(gdb) run
Starting program: /home/sakari/builds/lovetext/lovetext 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffebfd4700 (LWP 31684)]
[MESSAGE] Program activated.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4d49ca2 in vfprintf () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff4d49ca2 in vfprintf () from /usr/lib/libc.so.6
#1  0x00007ffff4df781b in __vfprintf_chk () from /usr/lib/libc.so.6
#2  0x00007ffff59a9d69 in g_printf () from /usr/lib/libglib-2.0.so.0
#3  0x000000000040e31b in alloc_preferences () at module.c:50
#4  0x0000000000406715 in main_application_activate (application=0x6271a0, user_data=0x628d70) at main.c:117
#5  0x00007ffff5c3b255 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff5c4cf4c in ?? () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff5c55758 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff5c559bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#9  0x00000000004066c6 in main_application_command_line (application=0x6271a0, command_line=0x77a160, user_data=0x628d70) at main.c:102
#10 0x00007ffff073d1f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#11 0x00007ffff073cc58 in ffi_call () from /usr/lib/libffi.so.6
#12 0x00007ffff5c3ba74 in g_cclosure_marshal_generic () from /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff5c3b255 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff5c4cf4c in ?? () from /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff5c55265 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff5c559bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff5f1ede3 in ?? () from /usr/lib/libgio-2.0.so.0
#18 0x00007ffff5f20dcd in ?? () from /usr/lib/libgio-2.0.so.0
#19 0x00007ffff5f20f77 in g_application_run () from /usr/lib/libgio-2.0.so.0
#20 0x0000000000406a4b in main (argc=1, args=0x7fffffffe058) at main.c:188
```

**Comment by FelipeFS** [comment]
Strange, at ```alloc_preferences()``` I'm using ```getenv()``` to recieve the "HOME" system variable. After NULL checking the variable, the ```g_printf()``` reports the value of "HOME", this is where the error seems to occur. I will try changing ```getenv()``` to ```g_get_home_dir()```. Thank you for your help!

**Comment by FelipeFS** [comment]
As stated by @Trilby at https://bbs.archlinux.org/viewtopic.php?id=193515, the error was the fact that "stdlib.h" was not included. The argument "-w" on the compiler was hiding the error. The ```getenv()``` was changed to ```g_get_home_dir()```, anyway, and stdlib.h was included.

**Comment by miko** [comment]
Works forme now. Thanks.

**Comment by flannelhead** [comment]
Yep, I'm also confirming that it works now. Thank you!

**Comment by FelipeFS** [comment]
=D
Thank you for the support!
